// Settings.Designer.cs 
//
//  Copyright (C) 2008 Fullsix Marketing Interactivo LDA
//  Copyright (C) 2008 Marco Cecconi
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA 
//

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SixPack.Properties {
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^(\\+|00)\\d+$")]
        public string Globalization_Portugal_PhoneNumber_PhonePattern_International {
            get {
                return ((string)(this["Globalization_Portugal_PhoneNumber_PhonePattern_International"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^1\\d+$")]
        public string Globalization_Portugal_PhoneNumber_PhonePattern_ShortNumber {
            get {
                return ((string)(this["Globalization_Portugal_PhoneNumber_PhonePattern_ShortNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^2[1-9]\\d{8}$")]
        public string Globalization_Portugal_PhoneNumber_PhonePattern_FixedService {
            get {
                return ((string)(this["Globalization_Portugal_PhoneNumber_PhonePattern_FixedService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^3\\d$+")]
        public string Globalization_Portugal_PhoneNumber_PhonePattern_NomadicService {
            get {
                return ((string)(this["Globalization_Portugal_PhoneNumber_PhonePattern_NomadicService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^6\\d+$")]
        public string Globalization_Portugal_PhoneNumber_PhonePattern_AudioText {
            get {
                return ((string)(this["Globalization_Portugal_PhoneNumber_PhonePattern_AudioText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^7\\d+$")]
        public string Globalization_Portugal_PhoneNumber_PhonePattern_PrivateVoiceNetwork {
            get {
                return ((string)(this["Globalization_Portugal_PhoneNumber_PhonePattern_PrivateVoiceNetwork"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^8\\d+$")]
        public string Globalization_Portugal_PhoneNumber_PhonePattern_FreeServices {
            get {
                return ((string)(this["Globalization_Portugal_PhoneNumber_PhonePattern_FreeServices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^9(1|2|6|3)\\d+$")]
        public string Globalization_Portugal_PhoneNumber_PhonePattern_MobileCommunicationServices {
            get {
                return ((string)(this["Globalization_Portugal_PhoneNumber_PhonePattern_MobileCommunicationServices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^\\d{4}-\\d{3}$")]
        public string Globalization_Portugal_PostalCode_PostalCodePattern {
            get {
                return ((string)(this["Globalization_Portugal_PostalCode_PostalCodePattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^\\d{9}$")]
        public string Globalization_Portugal_FiscalCode_FiscalCodePattern {
            get {
                return ((string)(this["Globalization_Portugal_FiscalCode_FiscalCodePattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^(PT){0,1}[0-9]{9}$")]
        public string Globalization_Portugal_VatCode_VatCodePattern {
            get {
                return ((string)(this["Globalization_Portugal_VatCode_VatCodePattern"]));
            }
        }
    }
}
