// UnicodeRange.cs 
//
//  Copyright (C) 2008 Fullsix Marketing Interactivo LDA
//  Author: Marco Cecconi
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA 
//

// UnicodeRanges.cs created with MonoDevelop
// User: marco at 1:05 PM 6/23/2008
//
// To change standard headers go to Edit->Preferences->Coding->Standard Headers
//

using System;

namespace SixPack.Text
{
	/// <summary>
	/// Represents the valid ranges of Unicode
	/// </summary>
	public enum UnicodeRange
	{
		// ... is not documented
#pragma warning disable 1591
		BasicLatin = 0,
		Latin1Supplement = 1,
		LatinExtendedA = 2,
		LatinExtendedB = 3,
		IPAExtensions = 4,
		SpacingModifierLetters = 5,
		CombiningDiacriticalMarks = 6,
		GreekandCoptic = 7,
		Cyrillic = 8,
		CyrillicSupplement = 9,
		Armenian = 10,
		Hebrew = 11,
		Arabic = 12,
		Syriac = 13,
		ArabicSupplement = 14,
		Thaana = 15,
		NKo = 16,
		//Undefined = 17,
		Devanagari = 18,
		Bengali = 19,
		Gurmukhi = 20,
		Gujarati = 21,
		Oriya = 22,
		Tamil = 23,
		Telugu = 24,
		Kannada = 25,
		Malayalam = 26,
		Sinhala = 27,
		Thai = 28,
		Lao = 29,
		Tibetan = 30,
		Myanmar = 31,
		Georgian = 32,
		HangulJamo = 33,
		Ethiopic = 34,
		EthiopicSupplement = 35,
		Cherokee = 36,
		UnifiedCanadianAboriginalSyllabics = 37,
		Ogham = 38,
		Runic = 39,
		Tagalog = 40,
		Hanunoo = 41,
		Buhid = 42,
		Tagbanwa = 43,
		Khmer = 44,
		Mongolian = 45,
		//Undefined = 46,
		Limbu = 47,
		TaiLe = 48,
		NewTaiLue = 49,
		KhmerSymbols = 50,
		Buginese = 51,
		//Undefined = 52,
		Balinese = 53,
		//Undefined = 54,
		PhoneticExtensions = 55,
		PhoneticExtensionsSupplement = 56,
		CombiningDiacriticalMarksSupplement = 57,
		LatinExtendedAdditional = 58,
		GreekExtended = 59,
		GeneralPunctuation = 60,
		SuperscriptsandSubscripts = 61,
		CurrencySymbols = 62,
		CombiningDiacriticalMarksforSymbols = 63,
		LetterlikeSymbols = 64,
		NumberForms = 65,
		Arrows = 66,
		MathematicalOperators = 67,
		MiscellaneousTechnical = 68,
		ControlPictures = 69,
		OpticalCharacterRecognition = 70,
		EnclosedAlphanumerics = 71,
		BoxDrawing = 72,
		BlockElements = 73,
		GeometricShapes = 74,
		MiscellaneousSymbols = 75,
		Dingbats = 76,
		MiscellaneousMathematicalSymbolsA = 77,
		SupplementalArrowsA = 78,
		BraillePatterns = 79,
		SupplementalArrowsB = 80,
		MiscellaneousMathematicalSymbolsB = 81,
		SupplementalMathematicalOperators = 82,
		MiscellaneousSymbolsandArrows = 83,
		Glagolitic = 84,
		LatinExtendedC = 85,
		Coptic = 86,
		GeorgianSupplement = 87,
		Tifinagh = 88,
		EthiopicExtended = 89,
		SupplementalPunctuation = 90,
		CJKRadicalsSupplement = 91,
		KangxiRadicals = 92,
		IdeographicDescriptionCharacters = 93,
		CJKSymbolsandPunctuation = 94,
		Hiragana = 95,
		Katakana = 96,
		Bopomofo = 97,
		HangulCompatibilityJamo = 98,
		Kanbun = 99,
		BopomofoExtended = 100,
		CJKStrokes = 101,
		KatakanaPhoneticExtensions = 102,
		EnclosedCJKLettersandMonths = 103,
		CJKCompatibility = 104,
		CJKUnifiedIdeographsExtensionA = 105,
		YijingHexagramSymbols = 106,
		CJKUnifiedIdeographs = 107,
		YiSyllables = 108,
		YiRadicals = 109,
		//Undefined = 110,
		ModifierToneLetters = 111,
		LatinExtendedD = 112,
		SylotiNagri = 113,
		//Undefined = 114,
		Phagspa = 115,
		//Undefined = 116,
		HangulSyllables = 117,
		//Undefined = 118,
		HighSurrogates = 119,
		HighPrivateUseSurrogates = 120,
		LowSurrogates = 121,
		PrivateUseAreaConlangTengwar = 122,
		PrivateUseAreaAreaConlangbrieCirth = 123,
		PrivateUseAreaConlangXaini = 124,
		PrivateUseAreaConlangMizarian = 125,
		PrivateUseAreaConlangZirinka = 126,
		PrivateUseAreaConlangSarkai = 127,
		PrivateUseAreaConlangThelwik = 128,
		PrivateUseAreaConlangOlaetyan = 129,
		PrivateUseAreaConlangNiskloz = 130,
		PrivateUseAreaConlangKazatakkorou = 131,
		PrivateUseAreaConlangKazvarad = 132,
		PrivateUseAreaConlangZarkhand = 133,
		PrivateUseAreaConlangRozhxh = 134,
		PrivateUseAreaConlangSerivelna = 135,
		PrivateUseAreaConlangKelwathi = 136,
		PrivateUseAreaConlangSaklor = 137,
		PrivateUseAreaConlangRynnan = 138,
		PrivateUseAreaConlangAlzetjan = 139,
		PrivateUseAreaConlangTelarasso = 140,
		PrivateUseAreaConlangSsuraki = 141,
		PrivateUseAreaConlangGargoyle = 142,
		PrivateUseAreaConlangOphidian = 143,
		PrivateUseAreaConlangFerengi = 144,
		PrivateUseAreaConlangSeussianLatinExtensions = 145,
		//PrivateUseArea = 146,
		PrivateUseAreaConlangEwellic = 147,
		PrivateUseAreaConlangPhaistosDisc = 148,
		PrivateUseAreaConlangUnifon = 149,
		PrivateUseAreaConlangSolresol = 150,
		PrivateUseAreaConlangVisibleSpeech = 151,
		PrivateUseAreaConlangMonofon = 152,
		//PrivateUseArea = 153,
		PrivateUseAreaHungarianRunes = 154,
		//PrivateUseArea = 155,
		PrivateUseAreaConlangAiha = 156,
		PrivateUseAreaConlangKlingon = 157,
		CJKCompatibilityIdeographs = 158,
		AlphabeticPresentationForms = 159,
		ArabicPresentationFormsA = 160,
		VariationSelectors = 161,
		VerticalForms = 162,
		CombiningHalfMarks = 163,
		CJKCompatibilityForms = 164,
		SmallFormVariants = 165,
		ArabicPresentationFormsB = 166,
		HalfwidthandFullwidthForms = 167,
		Specials = 168,
		//LinearBSyllabary = 169,
		//LinearBIdeograms = 170,
		//AegeanNumbers = 171,
		//AncientGreekNumbers = 172,
		//Undefined = 173,
		//OldItalic = 174,
		//Gothic = 175,
		//Ugaritic = 176,
		//OldPersian = 177,
		//Deseret = 178,
		//Shavian = 179,
		//Osmanya = 180,
		//CypriotSyllabary = 181,
		//Undefined = 182,
		//Phoenician = 183,
		//Kharoshthi = 184,
		//Undefined = 185,
		//Cuneiform = 186,
		//CuneiformNumbersandPunctuation = 187,
		//Undefined = 188,
		//ByzantineMusicalSymbols = 189,
		//MusicalSymbols = 190,
		//AncientGreekMusicalNotation = 191,
		//Undefined = 192,
		//TaiXuanJingSymbols = 193,
		//CountingRodNumerals = 194,
		//Undefined = 195,
		//MathematicalAlphanumericSymbols = 196,
		//Undefined = 197,
		//CJKUnifiedIdeographsExtensionB = 198,
		//Undefined = 199,
		//CJKCompatibilityIdeographsSupplement = 200,
		//Unused = 201,
		//Tags = 202,
		//Unused = 203,
		//VariationSelectorsSupplement = 204,
		//Unused = 205,
		//SupplementaryPrivateUseAreaAConlangKinyaSyllables = 206,
		//SupplementaryPrivateUseAreaAConlangPikto = 207,
		//SupplementaryPrivateUseAreaA = 208,
		//SupplementaryPrivateUseAreaB = 209,
#pragma warning restore 1591
	}
}
